<?php
// database/migrations/2024_06_01_000001_upgrade_lessons_for_cloudinary.php
//
// Run: php artisan migrate

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        Schema::table('lessons', function (Blueprint $table) {
            // Store the raw Cloudinary streaming URL (for <video> tag)
            $table->string('video_url', 1000)->nullable()->after('video_file_id');

            // Store the Cloudinary public_id for management (delete, transform)
            $table->string('cloudinary_public_id', 500)->nullable()->after('video_url');

            // Thumbnail URL (auto-generated by Cloudinary)
            $table->string('thumbnail_url', 1000)->nullable()->after('cloudinary_public_id');

            // Update enum to include cloudinary
            // MySQL requires MODIFY COLUMN to change enum
        });

        // Extend the enum to include 'cloudinary'
        DB::statement("ALTER TABLE lessons MODIFY COLUMN video_source ENUM('google_drive','youtube','url','cloudinary') DEFAULT 'google_drive'");
    }

    public function down(): void
    {
        // Revert enum first
        DB::statement("ALTER TABLE lessons MODIFY COLUMN video_source ENUM('google_drive','youtube','url') DEFAULT 'google_drive'");

        Schema::table('lessons', function (Blueprint $table) {
            $table->dropColumn(['video_url', 'cloudinary_public_id', 'thumbnail_url']);
        });
    }
};
